"""Shared graph engine library -- SQLite-backed concept store."""

from graph.diagnostics import DiagnosticReport, diagnose_graph
from graph.engine import (
    AdmissibilityError,
    add_edge,
    add_node,
    compare_neighborhoods,
    delete_edge,
    delete_node,
    get_edge,
    get_node,
    list_nodes,
    match_scenarios,
    neighbors,
    path_exists,
    query_by_attrs,
    query_edges_by_attrs,
    ranked_recommendations,
    subgraph_around,
    transitive_impact,
    update_node_attrs,
    validate_graph,
)
from graph.optimization import (
    create_comparative_analysis,
    create_kernel,
    create_optimization_goal,
    create_use_case_scenario,
    link_concept_to_goal,
    link_concept_to_kernel,
    link_concept_to_scenario,
)
from graph.rules import Violation, validate_node
from graph.schema import (
    EDGE_KINDS,
    EDGE_VALID_PAIRS,
    NODE_KINDS,
    REQUIRED_ATTRS,
    init_db,
)

__all__ = [
    "AdmissibilityError",
    "DiagnosticReport",
    "EDGE_KINDS",
    "EDGE_VALID_PAIRS",
    "NODE_KINDS",
    "REQUIRED_ATTRS",
    "Violation",
    "add_edge",
    "add_node",
    "compare_neighborhoods",
    "create_comparative_analysis",
    "create_kernel",
    "create_optimization_goal",
    "create_use_case_scenario",
    "diagnose_graph",
    "delete_edge",
    "delete_node",
    "get_edge",
    "get_node",
    "init_db",
    "link_concept_to_goal",
    "link_concept_to_kernel",
    "link_concept_to_scenario",
    "list_nodes",
    "match_scenarios",
    "neighbors",
    "path_exists",
    "query_by_attrs",
    "query_edges_by_attrs",
    "ranked_recommendations",
    "subgraph_around",
    "transitive_impact",
    "update_node_attrs",
    "validate_graph",
    "validate_node",
]
